export const REMOVE_RESERVATION = 'REMOVE_RESERVATION';
export const RECEIVE_RESERVATIONS = 'RECEIVE_RESERVATIONS';
export const ADD_RESERVATION = 'ADD_RESERVATION';
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER'; 